spring.application.name=order
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=none


# flyway helps us to version control our database migrations easily. or liquid base
#flyway.user=root
#flyway.password=mysql
#flyway.url=jdbc:mysql://localhost:3306/order_service



server.port=8081