spring.application.name=food
spring.mongodb.uri=mongodb://localhost:27017/crave-food-service?authSource=admin

springdoc.api-docs.path=/docs
springdoc.api-docs.enabled=true



# this is used to test the server
#server.tomcat.threads.max=1


